// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {req} from '../models';
import {res} from '../models';
import {api} from '../models';

export function Add(arg1:req.AppReq):Promise<res.BaseRes>;

export function Delete(arg1:string):Promise<res.BaseRes>;

export function ExecuteSQL():Promise<res.BaseRes>;

export function GetAppHomePath():Promise<api.AppManager>;

export function GetById(arg1:string):Promise<res.BaseRes>;

export function List():Promise<res.BaseRes>;

export function Process():Promise<res.BaseRes>;

export function RefreshPorts(arg1:string):Promise<res.BaseRes>;

export function Restart(arg1:string):Promise<res.BaseRes>;

export function RestartAll():Promise<res.BaseRes>;

export function Start(arg1:string):Promise<res.BaseRes>;

export function StartAll(arg1:Array<string>):Promise<res.BaseRes>;

export function Status(arg1:string):Promise<res.BaseRes>;

export function Stop(arg1:string):Promise<res.BaseRes>;

export function StopAll(arg1:Array<string>):Promise<res.BaseRes>;

export function Update(arg1:req.AppReq):Promise<res.BaseRes>;
