// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['api']['AppManager']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['api']['AppManager']['Delete'](arg1);
}

export function ExecuteSQL() {
  return window['go']['api']['AppManager']['ExecuteSQL']();
}

export function GetAppHomePath() {
  return window['go']['api']['AppManager']['GetAppHomePath']();
}

export function GetById(arg1) {
  return window['go']['api']['AppManager']['GetById'](arg1);
}

export function List() {
  return window['go']['api']['AppManager']['List']();
}

export function Process() {
  return window['go']['api']['AppManager']['Process']();
}

export function RefreshPorts(arg1) {
  return window['go']['api']['AppManager']['RefreshPorts'](arg1);
}

export function Restart(arg1) {
  return window['go']['api']['AppManager']['Restart'](arg1);
}

export function RestartAll() {
  return window['go']['api']['AppManager']['RestartAll']();
}

export function Start(arg1) {
  return window['go']['api']['AppManager']['Start'](arg1);
}

export function StartAll(arg1) {
  return window['go']['api']['AppManager']['StartAll'](arg1);
}

export function Status(arg1) {
  return window['go']['api']['AppManager']['Status'](arg1);
}

export function Stop(arg1) {
  return window['go']['api']['AppManager']['Stop'](arg1);
}

export function StopAll(arg1) {
  return window['go']['api']['AppManager']['StopAll'](arg1);
}

export function Update(arg1) {
  return window['go']['api']['AppManager']['Update'](arg1);
}
