// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFileExplorer(arg1) {
  return window['go']['api']['CommManager']['OpenFileExplorer'](arg1);
}
