// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {res} from '../models';

export function GetDashboard():Promise<res.OverviewData>;
