// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['api']['EnvManager']['Add'](arg1);
}

export function CheckEnvVars(arg1) {
  return window['go']['api']['EnvManager']['CheckEnvVars'](arg1);
}

export function Delete(arg1) {
  return window['go']['api']['EnvManager']['Delete'](arg1);
}

export function Detail(arg1) {
  return window['go']['api']['EnvManager']['Detail'](arg1);
}

export function GetEnvHomePath() {
  return window['go']['api']['EnvManager']['GetEnvHomePath']();
}

export function List() {
  return window['go']['api']['EnvManager']['List']();
}

export function Update(arg1) {
  return window['go']['api']['EnvManager']['Update'](arg1);
}
