// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {req} from '../models';
import {res} from '../models';
import {api} from '../models';

export function Add(arg1:req.EnvReqAdd):Promise<res.BaseRes>;

export function CheckEnvVars(arg1:req.EnvCheckReq):Promise<res.BaseRes>;

export function Delete(arg1:string):Promise<res.BaseRes>;

export function Detail(arg1:string):Promise<res.BaseRes>;

export function GetEnvHomePath():Promise<api.EnvManager>;

export function List():Promise<res.BaseRes>;

export function Update(arg1:req.EnvReqAdd):Promise<res.BaseRes>;
