// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGlobalSetting() {
  return window['go']['api']['GlobalSettingManager']['GetGlobalSetting']();
}

export function SetGlobalSetting(arg1) {
  return window['go']['api']['GlobalSettingManager']['SetGlobalSetting'](arg1);
}
