// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {res} from '../models';
import {model} from '../models';

export function GetGlobalSetting():Promise<res.BaseRes>;

export function SetGlobalSetting(arg1:model.GlobalSetting):Promise<res.BaseRes>;
