// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {res} from '../models';

export function AppLog(arg1:string):Promise<res.BaseRes>;

export function CloseAppLog(arg1:string):Promise<res.BaseRes>;

export function CloseSystemLog():Promise<res.BaseRes>;

export function SystemLog():Promise<res.BaseRes>;
