// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppLog(arg1) {
  return window['go']['api']['LogManager']['AppLog'](arg1);
}

export function CloseAppLog(arg1) {
  return window['go']['api']['LogManager']['CloseAppLog'](arg1);
}

export function CloseSystemLog() {
  return window['go']['api']['LogManager']['CloseSystemLog']();
}

export function SystemLog() {
  return window['go']['api']['LogManager']['SystemLog']();
}
