// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function Cpu():Promise<string>;

export function Disk():Promise<string>;

export function Gpu():Promise<string>;

export function HomeOsInfo():Promise<dto.HomeOsInfo>;

export function Memory():Promise<string>;

export function Network():Promise<string>;

export function OsInfo():Promise<dto.SystemInfo>;

export function Process():Promise<string>;
