// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cpu() {
  return window['go']['api']['SystemOs']['Cpu']();
}

export function Disk() {
  return window['go']['api']['SystemOs']['Disk']();
}

export function Gpu() {
  return window['go']['api']['SystemOs']['Gpu']();
}

export function HomeOsInfo() {
  return window['go']['api']['SystemOs']['HomeOsInfo']();
}

export function Memory() {
  return window['go']['api']['SystemOs']['Memory']();
}

export function Network() {
  return window['go']['api']['SystemOs']['Network']();
}

export function OsInfo() {
  return window['go']['api']['SystemOs']['OsInfo']();
}

export function Process() {
  return window['go']['api']['SystemOs']['Process']();
}
